package com.example.smart_ticket_router.entity;

import com.example.smart_ticket_router.enums.AssignedTeam;
import com.example.smart_ticket_router.enums.Priority;
import com.example.smart_ticket_router.enums.TicketCategory;
import com.example.smart_ticket_router.enums.TicketStatus;
import jakarta.persistence.*;

import java.time.LocalDateTime;

/**
 * Entity representing a support ticket submitted by a user.
 *
 * <p>Each ticket contains the original message, AI-generated
 * classification details such as category, priority, assigned team,
 * and the reasoning behind the classification. A ticket is associated
 * with a single user and stores its creation timestamp.
 */
@Entity
@Table(name = "tickets")
public class Ticket {

    /**
     * Unique identifier for the ticket.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Original support ticket message submitted by the user.
     */
    @Column(columnDefinition = "TEXT")
    private String message;

    /**
     * AI-predicted ticket category.
     */
    @Enumerated(EnumType.STRING)
    private TicketCategory category;

    /**
     * AI-predicted priority level.
     */
    @Enumerated(EnumType.STRING)
    private Priority priority;

    /**
     * Team assigned to resolve the ticket.
     */
    @Enumerated(EnumType.STRING)
    private AssignedTeam assignedTeam;

    /**
     * Explanation generated by the AI for the routing decision.
     */
    @Column(columnDefinition = "TEXT")
    private String reason;

    /**
     * User who submitted the ticket.
     */
    @ManyToOne
    @JoinColumn(name = "user_id")
    private User user;

    /**
     * Current workflow status of the ticket (open, in progress,
     * resolved or closed).
     *
     * <p>
     * A database-level default of {@code OPEN} is declared so that,
     * when this column is first added to an existing {@code tickets}
     * table by Hibernate ({@code spring.jpa.hibernate.ddl-auto=update}),
     * pre-existing rows are backfilled with {@code OPEN} instead of
     * being left {@code NULL}.
     * </p>
     */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false, columnDefinition = "varchar(20) default 'OPEN'")
    private TicketStatus status = TicketStatus.OPEN;

    /**
     * Timestamp indicating when the ticket was created.
     */
    private LocalDateTime createdAt;

    /**
     * Default constructor required by JPA.
     */
    public Ticket() {
    }

    /**
     * Sets the creation timestamp automatically before the entity
     * is persisted to the database.
     */
    @PrePersist
    public void prePersist() {
        this.createdAt = LocalDateTime.now();
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    public TicketCategory getCategory() {
        return category;
    }

    public void setCategory(TicketCategory category) {
        this.category = category;
    }

    public Priority getPriority() {
        return priority;
    }

    public void setPriority(Priority priority) {
        this.priority = priority;
    }

    public AssignedTeam getAssignedTeam() {
        return assignedTeam;
    }

    public void setAssignedTeam(AssignedTeam assignedTeam) {
        this.assignedTeam = assignedTeam;
    }

    public String getReason() {
        return reason;
    }

    public void setReason(String reason) {
        this.reason = reason;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public TicketStatus getStatus() {
        return status;
    }

    public void setStatus(TicketStatus status) {
        this.status = status;
    }
}