package com.example.smart_ticket_router.client;

import java.util.List;
import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.http.MediaType;
import org.springframework.stereotype.Component;
import org.springframework.web.client.RestClient;

/**
 * Client responsible for communicating with the OpenAI API.
 *
 * <p>This client provides methods to:
 * <ul>
 *     <li>Generate ticket routing responses using Chat Completions.</li>
 *     <li>Generate vector embeddings for ticket messages.</li>
 * </ul>
 */
@Component
public class OpenAIClient {

    private static final Logger logger =
            LoggerFactory.getLogger(OpenAIClient.class);

    /**
     * OpenAI API key configured in application.properties.
     */
    @Value("${openai.api.key}")
    private String apiKey;

    /**
     * Chat completion model.
     */
    @Value("${openai.model}")
    private String model;

    /**
     * Embedding model.
     */
    @Value("${openai.embedding.model}")
    private String embeddingModel;

    /**
     * REST client used for communicating with the OpenAI API.
     */
    private final RestClient restClient = RestClient.create();

    /**
     * Sends a prompt to the OpenAI Chat Completions API.
     *
     * <p>The model is instructed to return only valid JSON,
     * which is later parsed into a {@code TicketResponse}.
     *
     * @param prompt prompt containing the ticket details
     * @return JSON response generated by OpenAI
     */
    public String askOpenAI(String prompt) {

        logger.info("Sending chat completion request to OpenAI.");
        logger.debug("Using model: {}", model);

        Map<String, Object> body = Map.of(
                "model", model,
                "messages", List.of(
                        Map.of(
                                "role", "system",
                                "content", "Return only valid JSON."
                        ),
                        Map.of(
                                "role", "user",
                                "content", prompt
                        )
                ),
                "temperature", 0
        );

        Map<?, ?> response = restClient.post()
                .uri("https://api.openai.com/v1/chat/completions")
                .contentType(MediaType.APPLICATION_JSON)
                .header("Authorization", "Bearer " + apiKey)
                .body(body)
                .retrieve()
                .body(Map.class);

        logger.info("Received chat completion response from OpenAI.");

        List<?> choices = (List<?>) response.get("choices");
        Map<?, ?> choice = (Map<?, ?>) choices.get(0);
        Map<?, ?> message = (Map<?, ?>) choice.get("message");

        String content = message.get("content").toString();

        logger.debug("OpenAI response content: {}", content);

        return content;
    }

    /**
     * Generates an embedding vector for the supplied text.
     *
     * <p>The embedding can be stored in ChromaDB and later used
     * for semantic similarity search.
     *
     * @param text text to convert into an embedding
     * @return embedding vector
     */
    @SuppressWarnings("unchecked")
    public List<Float> getEmbedding(String text) {

        logger.info("Generating embedding using OpenAI.");
        logger.debug("Using embedding model: {}", embeddingModel);

        Map<String, Object> request = Map.of(
                "model", embeddingModel,
                "input", text
        );

        Map<String, Object> response = restClient.post()
                .uri("https://api.openai.com/v1/embeddings")
                .header("Authorization", "Bearer " + apiKey)
                .contentType(MediaType.APPLICATION_JSON)
                .body(request)
                .retrieve()
                .body(Map.class);

        List<Map<String, Object>> data =
                (List<Map<String, Object>>) response.get("data");

        Map<String, Object> firstEmbedding = data.get(0);

        List<Double> embedding =
                (List<Double>) firstEmbedding.get("embedding");

        logger.info("Embedding generated successfully.");
        logger.debug("Embedding vector size: {}", embedding.size());

        return embedding.stream()
                .map(Double::floatValue)
                .toList();
    }
}